const modelsPassage = `A scientific model is useful because it leaves things out. A transit map ignores street width and exact distance so that a traveler can see connections quickly. The same simplification can be dangerous when the omitted feature matters to the decision being made. A flood model calibrated on historical rainfall may appear accurate until a changing climate makes those records less representative. The right response is neither to demand a perfect copy of reality nor to trust a model because its past predictions were good. Users should ask what the model preserves, what it discards, and whether those choices remain appropriate for the task. Sometimes two imperfect models, built with different assumptions, reveal more than a single detailed one.`;
const heatPassage = `Cities often report one average temperature, but heat risk is uneven. A shaded street and a nearby unshaded road can differ sharply, while people without reliable water or cooling may face greater harm at the same temperature. Planting trees helps, yet it cannot solve every part of the problem: roofs, street geometry, airflow, and building materials also affect exposure. A city that measures only where sensors are easy to install may miss the neighborhoods most at risk. Effective policy therefore needs local measurement together with attention to who can actually use the proposed remedies. More data is valuable only if the measurement design does not hide the people the policy aims to protect.`;

export const challengeBank = [
  { id:'cv1',section:'VARC',topic:'rc-main',type:'MCQ',difficulty:'Hard',passage:modelsPassage,q:'Which statement best expresses the author\'s main claim?',options:['Scientific models should be discarded once climate patterns change.','A model should be judged by whether its simplifications suit the decision, not by detail alone.','Transit maps are more reliable than flood models because they omit more detail.','Past predictive accuracy guarantees future usefulness when models are compared.'],answer:1,solution:'The passage argues that omissions are useful or dangerous depending on the task and changing conditions.' },
  { id:'cv2',section:'VARC',topic:'rc-inference',type:'MCQ',difficulty:'Hard',passage:modelsPassage,q:'Which inference is most strongly supported?',options:['A detailed model always contains more actionable information.','Two models with different assumptions may expose a hidden weakness in each other.','Historical data should never be used in flood models.','Every model should preserve exact distances.'],answer:1,solution:'The final sentence says two models with different assumptions can reveal more than one detailed model.' },
  { id:'cv3',section:'VARC',topic:'rc-application',type:'MCQ',difficulty:'Medium',passage:modelsPassage,q:'Which use of a model best follows the author\'s recommendation?',options:['Choosing a flood model solely by the number of variables it contains.','Using an old model unchanged because it performed well ten years ago.','Checking whether a model built for national forecasts is suitable for a specific flood-prone street.','Rejecting a transit map because it omits the width of each road.'],answer:2,solution:'The recommendation is to test whether the model\'s retained and omitted features fit the decision.' },
  { id:'cv4',section:'VARC',topic:'rc-tone',type:'MCQ',difficulty:'Medium',passage:modelsPassage,q:'The author\'s attitude toward scientific models is best described as:',options:['unqualified enthusiasm','careful pragmatism','deep hostility','indifference'],answer:1,solution:'The author accepts their usefulness while requiring scrutiny of assumptions and context.' },
  { id:'cv5',section:'VARC',topic:'rc-main',type:'MCQ',difficulty:'Hard',passage:heatPassage,q:'The central concern of the passage is that urban heat policy should:',options:['replace all street sensors with satellite measurements','combine neighborhood-level exposure measurement with attention to unequal vulnerability','focus only on planting trees in the hottest streets','use one citywide temperature to make comparisons simple'],answer:1,solution:'Both local measurement and differential vulnerability are central to the argument.' },
  { id:'cv6',section:'VARC',topic:'rc-inference',type:'MCQ',difficulty:'Hard',passage:heatPassage,q:'Which inference follows about a policy based only on easy-to-install sensors?',options:['It may overlook neighborhoods that face the greatest harm.','It will necessarily overestimate average city temperature.','It makes trees ineffective as a remedy.','It removes the need to study housing and access to cooling.'],answer:0,solution:'The passage explicitly warns that convenient sensor placement can miss high-risk neighborhoods.' },
  { id:'cv7',section:'VARC',topic:'rc-argument',type:'MCQ',difficulty:'Medium',passage:heatPassage,q:'Which finding would most weaken a claim that planting trees alone is sufficient?',options:['Some residents prefer shaded sidewalks.','Roof reflectivity and airflow strongly influence indoor heat even on tree-lined streets.','Trees are costly to maintain.','One neighborhood has many older trees.'],answer:1,solution:'It shows that other factors remain important even where trees are present.' },
  { id:'cv8',section:'VARC',topic:'rc-detail',type:'MCQ',difficulty:'Medium',passage:heatPassage,q:'Which factor is NOT identified as affecting heat exposure?',options:['roof materials','street geometry','building materials','public transport fares'],answer:3,solution:'The passage names roofs, geometry, airflow, and materials, but not transport fares.' },

  { id:'cd1',section:'DILR',topic:'lr-arrange',type:'MCQ',difficulty:'Medium',set:'Six people A, B, C, D, E and F sit in a row facing north. C is third from the left. F is at the right end. A sits immediately left of B. D sits left of E. E is not fifth.',q:'Who sits second from the left?',options:['A','B','D','E'],answer:3,solution:'The only order satisfying every clue is D-E-C-A-B-F. E is second.' },
  { id:'cd2',section:'DILR',topic:'lr-arrange',type:'MCQ',difficulty:'Medium',set:'Six people A, B, C, D, E and F sit in a row facing north. C is third from the left. F is at the right end. A sits immediately left of B. D sits left of E. E is not fifth.',q:'How many people sit between D and B?',options:['2','3','4','1'],answer:1,solution:'The unique order is D-E-C-A-B-F. D is first and B fifth, leaving E,C,A between them.' },
  { id:'cd3',section:'DILR',topic:'lr-arrange',type:'MCQ',difficulty:'Medium',set:'Six people A, B, C, D, E and F sit in a row facing north. C is third from the left. F is at the right end. A sits immediately left of B. D sits left of E. E is not fifth.',q:'Who sits immediately to the right of C?',options:['A','B','D','E'],answer:0,solution:'In D-E-C-A-B-F, A is immediately right of C.' },
  { id:'cd4',section:'DILR',topic:'lr-arrange',type:'MCQ',difficulty:'Medium',set:'Six people A, B, C, D, E and F sit in a row facing north. C is third from the left. F is at the right end. A sits immediately left of B. D sits left of E. E is not fifth.',q:'Which pair occupies the two end seats?',options:['D and F','E and F','A and F','D and B'],answer:0,solution:'The unique order D-E-C-A-B-F has D and F at the ends.' },
  { id:'cd5',section:'DILR',topic:'di-tables',type:'TITA',difficulty:'Medium',set:'Sales at cafés P, Q, R. Monday tea/coffee: P 80/120, Q 100/80, R 60/90. Tuesday: P tea rises 25% and coffee falls 10%; Q tea is unchanged and coffee rises 25%; R tea rises 50% and coffee is unchanged.',q:'How many cups of tea were sold across all three cafés on Tuesday?',answer:'290',solution:'Tuesday tea: P 100, Q 100, R 90. Total = 290.' },
  { id:'cd6',section:'DILR',topic:'di-tables',type:'TITA',difficulty:'Hard',set:'Sales at cafés P, Q, R. Monday tea/coffee: P 80/120, Q 100/80, R 60/90. Tuesday: P tea rises 25% and coffee falls 10%; Q tea is unchanged and coffee rises 25%; R tea rises 50% and coffee is unchanged.',q:'How many more total cups were sold on Tuesday than Monday?',answer:'58',solution:'Monday total = 530. Tuesday P = 208, Q = 200, R = 180; total = 588. Difference = 58.' },
  { id:'cd7',section:'DILR',topic:'di-ratios',type:'TITA',difficulty:'Hard',set:'Sales at cafés P, Q, R. Monday tea/coffee: P 80/120, Q 100/80, R 60/90. Tuesday: P tea rises 25% and coffee falls 10%; Q tea is unchanged and coffee rises 25%; R tea rises 50% and coffee is unchanged.',q:'Give the ratio of Tuesday tea sales to Tuesday coffee sales in simplest form.',answer:'145:149',solution:'Tuesday tea = 290. Tuesday coffee = 108 + 100 + 90 = 298. Reduce 290:298 to 145:149.' },
  { id:'cd8',section:'DILR',topic:'di-charts',type:'MCQ',difficulty:'Medium',set:'Sales at cafés P, Q, R. Monday tea/coffee: P 80/120, Q 100/80, R 60/90. Tuesday: P tea rises 25% and coffee falls 10%; Q tea is unchanged and coffee rises 25%; R tea rises 50% and coffee is unchanged.',q:'Which café had the largest percentage increase in total sales from Monday to Tuesday?',options:['P','Q','R','P and Q tied'],answer:2,solution:'P: 200 to 208 = 4%. Q: 180 to 200 = 11.1%. R: 150 to 180 = 20%, largest.' },

  { id:'cq1',section:'QA',topic:'qa-pl',type:'TITA',difficulty:'Medium',q:'An article is marked 50% above cost price. After successive discounts of 10% and d%, the seller still earns 8% profit. Find d.',answer:'20',solution:'Let cost be 100. Marked price = 150; after 10% it is 135. To sell at 108, second factor is 108/135 = 0.8. Hence d = 20%.' },
  { id:'cq2',section:'QA',topic:'qa-mixture',type:'TITA',difficulty:'Hard',q:'A 30 L solution contains 40% acid. How many liters should be removed and replaced with water once to make it 30% acid?',answer:'7.5',solution:'Initial acid is 12 L. Removing x L removes 0.4x L acid. Final acid is 9 L, so 12 - 0.4x = 9 and x = 7.5 L.' },
  { id:'cq3',section:'QA',topic:'qa-tsd',type:'TITA',difficulty:'Medium',q:'A 180 m train passes a pole in 9 seconds. It passes a 120 m train traveling in the opposite direction in 10 seconds. Find the speed of the second train in km/h.',answer:'36',solution:'First train speed = 180/9 = 20 m/s. Relative speed = (180+120)/10 = 30 m/s. Second speed = 10 m/s = 36 km/h.' },
  { id:'cq4',section:'QA',topic:'qa-work',type:'TITA',difficulty:'Hard',q:'A can finish a job in 12 days and B in 18 days. They work together for 4 days, then A alone finishes the job. How many days does A work alone? Enter as a fraction.',answer:'16/3',solution:'Together they do 1/12 + 1/18 = 5/36 per day, or 5/9 in four days. Remaining work = 4/9. At 1/12 per day, A needs (4/9) x 12 = 16/3 days.' },
  { id:'cq5',section:'QA',topic:'qa-quadratic',type:'MCQ',difficulty:'Medium',q:'The roots of x² - 8x + k = 0 differ by 2. What is k?',options:['12','15','16','20'],answer:1,solution:'Roots sum to 8 and differ by 2, so they are 3 and 5. Their product k = 15.' },
  { id:'cq6',section:'QA',topic:'qa-remainder',type:'MCQ',difficulty:'Medium',q:'What is the remainder when 2^100 is divided by 7?',options:['1','2','4','6'],answer:1,solution:'Powers of 2 modulo 7 cycle 2,4,1 every three exponents. Since 100 leaves remainder 1 on division by 3, the result is 2.' },
  { id:'cq7',section:'QA',topic:'qa-geometry',type:'TITA',difficulty:'Medium',q:'A right triangle has legs 9 cm and 12 cm. Find the inradius in cm.',answer:'3',solution:'The hypotenuse is 15 cm. For a right triangle, inradius = (a+b-c)/2 = (9+12-15)/2 = 3 cm.' },
  { id:'cq8',section:'QA',topic:'qa-probability',type:'MCQ',difficulty:'Hard',q:'A bag has 5 red and 4 blue balls. Three are drawn without replacement. What is the probability of at least one red?',options:['5/9','20/21','5/6','10/21'],answer:1,solution:'Use the complement. Probability all three are blue = C(4,3)/C(9,3) = 4/84 = 1/21. So at least one red = 20/21.' },
  { id:'cq9',section:'QA',topic:'qa-pnc',type:'TITA',difficulty:'Hard',q:'A committee of 4 is selected from 5 men and 4 women. How many committees contain at least 2 women?',answer:'81',solution:'Exactly 2 women: C(4,2)C(5,2)=60. Exactly 3: C(4,3)C(5,1)=20. Exactly 4: C(4,4)=1. Total 81.' },
  { id:'cq10',section:'QA',topic:'qa-logs',type:'MCQ',difficulty:'Medium',q:'If log₂x + log₂(x - 2) = 3, what is x?',options:['2','3','4','6'],answer:2,solution:'Domain x > 2. Combine logs: x(x-2)=8, giving x²-2x-8=0. Roots are 4 and -2; only 4 is valid.' },
  { id:'cq11',section:'QA',topic:'qa-coordinate',type:'TITA',difficulty:'Medium',q:'The line through (2,3) and (6,11) also passes through (9,y). Find y.',answer:'17',solution:'Slope = (11-3)/(6-2)=2. From x=6 to x=9, y rises by 2 x 3 = 6, so y=17.' },
  { id:'cq12',section:'QA',topic:'qa-numbers',type:'TITA',difficulty:'Hard',q:'How many positive divisors of 2^4 x 3^2 are divisible by 12?',answer:'6',solution:'A divisor divisible by 12=2² x 3 needs exponent of 2 from 2 to 4 (3 choices) and exponent of 3 from 1 to 2 (2 choices). Total 6.' },
  { id:'cq13',section:'QA',topic:'qa-linear',type:'TITA',difficulty:'Hard',q:'Positive integers x and y satisfy 3x + 5y = 44. What is the maximum possible value of xy?',answer:'32',solution:'Modulo 3 gives 2y = 2, so y is 1 mod 3. Positive solutions are (x,y)=(13,1),(8,4),(3,7). Products are 13,32,21; maximum 32.' },
  { id:'cq14',section:'QA',topic:'qa-sets',type:'TITA',difficulty:'Medium',q:'In a survey of 120 people, 72 read newspaper A, 65 read B, and 30 read neither. How many read both?',answer:'47',solution:'Union = 120 - 30 = 90. Inclusion-exclusion gives intersection = 72 + 65 - 90 = 47.' },
  { id:'cq15',section:'QA',topic:'qa-average',type:'TITA',difficulty:'Medium',q:'The average of 8 numbers is 25. One number, 17, was recorded as 71. What is the correct average?',answer:'18.25',solution:'Recorded sum = 8 x 25 = 200. Correct sum = 200 - 71 + 17 = 146. Average = 146/8 = 18.25.' },
  { id:'cq16',section:'QA',topic:'qa-percent',type:'MCQ',difficulty:'Medium',q:'A population rises by 25% in one year and falls by 20% the next. What is its net percentage change?',options:['No change','5% increase','5% decrease','10% increase'],answer:0,solution:'The factors multiply: 1.25 x 0.80 = 1.00, so there is no net change.' },
  { id:'cd9',section:'DILR',topic:'lr-schedule',type:'TITA',difficulty:'Hard',set:'Six talks A, B, C, D, E, F occupy slots 1-6. A is before C. B is immediately before D. E is after C. F is neither first nor last.',q:'How many schedules satisfy all the conditions?',answer:'12',solution:'Treat B-D as a block. Enumerate its five possible placements, then place A-C-E in that order and F away from both ends. Exactly 12 schedules survive all constraints.' },
  { id:'cd10',section:'DILR',topic:'lr-schedule',type:'MCQ',difficulty:'Hard',set:'Six talks A, B, C, D, E, F occupy slots 1-6. A is before C. B is immediately before D. E is after C. F is neither first nor last.',q:'Which first/last pair is impossible?',options:['A first, E last','A first, D last','B first, E last','B first, D last'],answer:3,solution:'If B-D occupy the first two slots, D cannot also be last. The other listed pairs occur in valid schedules.' },
  { id:'cd11',section:'DILR',topic:'lr-schedule',type:'TITA',difficulty:'Hard',set:'Six talks A, B, C, D, E, F occupy slots 1-6. A is before C. B is immediately before D. E is after C. F is neither first nor last.',q:'How many valid schedules have B in the first slot?',answer:'3',solution:'Fix B-D in slots 1-2. Arrange A-C-E in order among remaining positions while F is not last. The valid sequences are B-D-A-C-F-E, B-D-A-F-C-E, and B-D-F-A-C-E.' }
];
